// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMUqX8hWaDPcz1B28Z7WLlTmWxVEVldiWY',
    authDomain: 'code-cracker-f3765.firebaseapp.com',
    projectId: 'code-cracker-f3765',
    storageBucket: 'code-cracker-f3765.appspot.com',
    messagingSenderId: '362101796226',
    appId: '1:362101796226:web:53af5bd5b80e91e96a339b',
    measurementId: 'G-BJHV8QJ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwuZHoJkDTRQacs096ZMn6NaRNqcreymw',
    appId: '1:362101796226:android:58c1bd8ecd82a61c6a339b',
    messagingSenderId: '362101796226',
    projectId: 'code-cracker-f3765',
    storageBucket: 'code-cracker-f3765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHMWZ8L5AEykikM9cruyx_aN9EXhuO1c',
    appId: '1:362101796226:ios:259b78042e8e2ce06a339b',
    messagingSenderId: '362101796226',
    projectId: 'code-cracker-f3765',
    storageBucket: 'code-cracker-f3765.appspot.com',
    iosBundleId: 'com.example.codeCracker',
  );
}
